### PR TITLE
Fix #46 and fixed some styling stuff

### LINKED ISSUE #46: .DS_STORE
We need to remove this file (If it exists) before making the folder into a DEB. The file is inside of the folder that is made before the DEB is packaged

It causes a cydia error

### PR DESCRIPTION
**Pull request by 1Conan**
#46

### CODE REVIEW

**Comment by EthanRDoesMC** [comment]
erm uh... @1Conan , mayyyyyyybe can we fix the conflicts?

**Comment by jonisc** [comment]
@EthanRDoesMC: I think he has already included his improvements in my pr.

**Comment by EthanRDoesMC** [comment]
I will keep it open until I can confirm.

**Comment by jonisc** [comment]
Correction: should be #50

**Pull request closed without merging**
