### PR TITLE
build.sh automatically edits eg. gandalf102 script so that you only have to edit build.sh

### PR DESCRIPTION
**Pull request by jonisc**
Can not explain... Just look at the code. it should work, but please test it at least twice before merge.

### CODE REVIEW

**Comment by jonisc** [comment]
.deb created with ubuntu VM. might not work?

**Comment by jonisc** [comment]
Nope: the app isn't installed correctly.

**Comment by EthanRDoesMC** [comment]
So... hold off?

**Comment by jonisc** [comment]
No. @mehulrao should look at it. I think something got deleted. The problem is that you have 2 gandalf.app 's one does only include the binary-> can't work and the other one is the big one -> should work. But I think he has to check what the problem is.

**Comment by jonisc** [comment]
I have a working gandalf.app directly from my phone. It's on the master branch (my master is not the branch I want to merge into your master!) please test it, but I think that it's really a problem with missing files.

**Comment by mehulrao** [comment]
@jonisc I think the app in the Gandalf folder should work just fine... Tell me when you are ready/want me to merge

**Comment by jonisc** [comment]
Hmm. Try to build it. Hopefully it works. The problem was that you have created 2 folders:
Gandalf.app (capitalized G)
And gandalf.app (lowercase g)
They aren't the same. You have placed the executable file in gandalf.app and the other things (like Icons, Info.plist) in Gandalf.app. So build.sh tar'ed gandalf.app and installed it on my iPhone to /Applications. But since there was only the binary(executable) iOS didn't know what to do with it. Now it doesn't show on the home screen. 

Now if you run build.sh it should fail: there's no folder called gandalf.app. Only one called Gandalf.app. So rename Gandalf.app to gandalf.app and everything should be ok.

**Comment by EthanRDoesMC** [comment]
Okay, on it. Dillanpocalypse happened as I slept.

**Comment by jonisc** [comment]
@1Conan fixed it I think. Thanks!

**Comment by 1Conan** [comment]
@jonisc what did I fix here? I think it's totally unrelated to my commits

**Comment by jonisc** [comment]
You have changed gandalf.app to Gandalf.app in build.sh. But the app is crashing I thought for a few seconds that you have fixed it since there was the Gandalf icon on my SpringBoard. 
I tried the den on /Gandalf @mehulrao should probably delete the .app & re add it to the repo (there's something wrong with the app)

**Comment by 1Conan** [comment]
I didn't modify the application part. I don't want to touch it.

**Comment by jonisc** [comment]
That's good. There was and currently is something wrong. But I think it was either me or someone else.

**Comment by EthanRDoesMC** [comment]
K, testing

**Pull request merged**
