### PR TITLE
Improve script; tried fixing readme, didn't work

### PR DESCRIPTION
**Pull request by jonisc**
So. Just an other PR from me. Made script better understandable, untested, will Test in a few minutes

### CODE REVIEW

**Comment by mehulrao** [comment]
Looks good

**Comment by mehulrao** [comment]
I'll wait for Ethan to see it before merging

**Comment by jonisc** [comment]
That's ok. I'm working on something… it's just a beta and just a small thought… look at my branch test.

**Comment by jonisc** [comment]
There's a small bug with the app on the SE: http://i.imgur.com/NQ0xmKo.png

**Comment by EthanRDoesMC** [comment]
*sees*

stupid toast notifications

reviewing

**Comment by EthanRDoesMC** [comment]
okay, i think the way links work may be based on protocols (so i can do this)[without problems]

**Comment by EthanRDoesMC** [comment]
yup, confirmed... readme.md cant have the whole URL... perhaps a bitly? Anyway, clearing up the info even more is something i thought was impossible... thanks for proving me wrong.

**Comment by jonisc** [comment]
I have just added a few words + formatting…

**Comment by EthanRDoesMC** [comment]
lol

**Comment by jonisc** [comment]
At "") and *) in the case please edit *to let Cydia remove it -> to let Cydia remove $GVERSIONNAME.

**Pull request merged**
